[tool.poetry]
name = "silx"
version = "2.1.1a0"
description = "Software library for X-ray data analysis"
authors = ["data analysis unit <silx@esrf.fr>"]
readme = "README.rst"

[build-system]
requires = [
    "wheel",
    "setuptools",
    "Cython>=0.29.31",
    "poetry-core",
]
build-backend = "setuptools.build_meta"

[tool.black]
required-version = 23
target-version = ["py37", "py38", "py39", "py310", "py311", "py312"]
safe = true

[tool.pytest.ini_options]
minversion = "6.0"
python_files = [
    "test/test*.py",
    "test/Test*.py",
]
python_classes = "Test"
python_functions = "test"
filterwarnings = [
    "error",
    # note the use of single quote below to denote "raw" strings in TOML
    'ignore:tostring\(\) is deprecated. Use tobytes\(\) instead\.:DeprecationWarning:OpenGL',
    'ignore:Jupyter is migrating its paths to use standard platformdirs:DeprecationWarning',
]
