[project]
name = "silx"
version = "2.2.0a0"
description = "Software library for X-ray data analysis"
authors = [{ name = "data analysis unit", email = "silx@esrf.fr" }]
requires-python = ">=3.8"
readme = "README.rst"
dependencies = [
    "cython>=0.29.31",
    "numpy>=1.14",
    "packaging",
    "h5py",
    "fabio>=0.9",
    'importlib_resources; python_version < "3.9"',
]

[project.optional-dependencies]
full = [
    'pyopencl; platform_machine in "i386,x86_64,AMD64"',
    "Mako",
    "qtconsole",
    "matplotlib>=3.1",
    "PyOpenGL",
    "python-dateutil",
    "scipy",
    "pooch",
    "Pillow",
    "pint",
    "pyqt5>=5.15.7,<6",
    "pyqt5-qt5==5.15.2",
]
dev = [
    "build",
    "wheel",
    "Sphinx",
    "sphinx-autodoc-typehints",
    "sphinx-design",
    "pillow",
    "pydata_sphinx_theme",
    "nbsphinx",
    "pandoc",
    "black[jupyter]",
    "pytest>=6",
    "pytest-xvfb",
    "pytest-cov",
    "pytest-mock",
    "hdf5plugin",
    'pyinstaller>=6.0.0; sys_platform == "win32"',
]

[build-system]
requires = [
    "wheel",
    "setuptools",
    "Cython>=0.29.31",
]
build-backend = "setuptools.build_meta"

[tool.black]
required-version = 23
target-version = ["py37", "py38", "py39", "py310", "py311", "py312"]
safe = true

[tool.pytest.ini_options]
minversion = "6.0"
python_files = [
    "test/test*.py",
    "test/Test*.py",
]
python_classes = "Test"
python_functions = "test"
filterwarnings = [
    "error",
    # note the use of single quote below to denote "raw" strings in TOML
    'ignore:tostring\(\) is deprecated. Use tobytes\(\) instead\.:DeprecationWarning:OpenGL',
    'ignore:Jupyter is migrating its paths to use standard platformdirs:DeprecationWarning',
]
